spring:
  application:
    name: SampleAliPay

mvf4ms:
  version: 2.3.1

server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://{REGISTRY_IP}:{REGISTRY_PORT}/eureka
